version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/mop-user-web
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
